### ISSUE TITLE
Error in caption prepare_dataset

### ISSUE THREAD

**Issue by ThomasEhling** [vsmolyakov/cv#1]
Hi,

Thank you very much for sharing this code !

When I download and run your code "prepare_dataset.py" from the "caption generation" folder, I have an error that rise.
I already used the Flickr8k dataset for other projects and it is installed on my computer. I made sure to update the path. Here is the error : 

`
94560256/94653016 [============================>.] - ETA: 0s
94658560/94653016 [==============================] - 52s 1us/step

94666752/94653016 [==============================] - 52s 1us/step
processing training and validation images...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/french_magician/Documents/Chicago/CV/Project/Code/prepare_dataset.py", line 107, in <module>
    c_train, c_val, c_test = prepare_dataset()
  File "/home/french_magician/Documents/Chicago/CV/Project/Code/prepare_dataset.py", line 71, in prepare_dataset
    encoded_images[img] = get_encoding(encoding_model, img)
  File "/home/french_magician/Documents/Chicago/CV/Project/Code/prepare_dataset.py", line 31, in get_encoding
    pred = np.reshape(pred, pred.shape[-1])
  File "/home/french_magician/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/french_magician/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 100352 into shape (2048,)
`

Do you know how to fix it ?

Thanks for your Help,
Thomas

**Comment by ThomasEhling** [comment]
The version of keras is the answer.
The latest version does not have a model the same image size.
